[package]
name = "rust_led_web_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
url = "2.2"
log = "0.4"
env_logger = "0.11.6"
rpi-led-panel = "0.6.0"